# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

   third_user = User.create(name: 'Tariq', photo: 'https://picsum.photos/300/200', bio: 'Teacher from Nigeria Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.')

   fourth_user = User.create(name: 'Mark', photo: 'https://picsum.photos/200/300', bio: 'Teacher from Kenya.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.')

  first_post = Post.create(author: third_user, title: 'Birthday', text: 'This is my first post')
  second_post = Post.create(author: third_user, title: 'Hi', text: 'This is my Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries post')
  third_post = Post.create(author: third_user, title: 'Dance', text: 'This is my third post')
  fourth_post = Post.create(author: third_user, title: 'December', text: 'This is my Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries post')
  fifth_post = Post.create(author: third_user, title: 'Holiday', text: 'This is my fifth post')
  sixth_post = Post.create(author: third_user, title: 'Black friday', text: 'This is my Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries post')

  seventh_post = Post.create(author: fourth_user, title: 'Jumia Offers', text: 'This is my first post')
  eighth_post = Post.create(author: fourth_user, title: 'Meeting of Family', text: 'This is my Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries post')
  nineth_post = Post.create(author: fourth_user, title: 'Wow!', text: 'This is my nineth post')
  tenth_post = Post.create(author: fourth_user, title: 'Season End', text: 'This is my Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries post')
  eleventh_post = Post.create(author: fourth_user, title: 'Sunny day', text: 'This is my eleventh post')
  twelveth_post = Post.create(author: fourth_user, title: 'Our Homeland', text: 'This is my Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries post')

  Comment.create(post: seventh_post, author: third_user, text: 'Hi Alex!' )
  Comment.create(post: seventh_post, author: third_user, text: 'Hi Alex!' )
  Comment.create(post: seventh_post, author: third_user, text: 'Hello Alex!' )
  Comment.create(post: seventh_post, author: third_user, text: 'Hello Alex!' )
  Comment.create(post: eighth_post, author: third_user, text: 'Hello Alex!' )
  Comment.create(post: eighth_post, author: third_user, text: 'Hello Alex!' )
  Comment.create(post: eighth_post, author: third_user, text: 'When is holiday' )
  Comment.create(post: eighth_post, author: third_user, text: 'When is holiday' )
  Comment.create(post: eighth_post, author: third_user, text: 'When is holiday' )
  Comment.create(post: nineth_post, author: third_user, text: 'When is holiday' )
  Comment.create(post: nineth_post, author: third_user, text: 'When is holiday' )
  Comment.create(post: nineth_post, author: third_user, text: 'When is holiday' )
  Comment.create(post: tenth_post, author: third_user, text: 'It was needed' )
  Comment.create(post: tenth_post, author: third_user, text: 'It was needed' )
  Comment.create(post: tenth_post, author: third_user, text: 'It was needed' )
  Comment.create(post: tenth_post, author: third_user, text: 'It was needed' )
  Comment.create(post: tenth_post, author: third_user, text: 'It was needed' )
  Comment.create(post: eleventh_post, author: third_user, text: 'It was needed' )
  Comment.create(post: eleventh_post, author: third_user, text: 'Sunny day today' )
  Comment.create(post: eleventh_post, author: third_user, text: 'Sunny day today' )
  Comment.create(post: twelveth_post, author: third_user, text: 'Sunny day today' )
  Comment.create(post: twelveth_post, author: third_user, text: 'Sunny day today' )
  Comment.create(post: twelveth_post, author: third_user, text: 'Sunny day today' )
  Comment.create(post: twelveth_post, author: third_user, text: 'Sunny day today' )

  Comment.create(post: first_post, author: fourth_user, text: 'Hi Ridwan!' )
  Comment.create(post: first_post, author: fourth_user, text: 'Hi Ridwan!' )
  Comment.create(post: first_post, author: fourth_user, text: 'Hi Ridwan!' )
  Comment.create(post: first_post, author: fourth_user, text: 'Hi Ridwan!' )
  Comment.create(post: first_post, author: fourth_user, text: 'Hi Ridwan!' )
  Comment.create(post: first_post, author: fourth_user, text: 'Hi Ridwan!' )
  Comment.create(post: first_post, author: fourth_user, text: 'Hi Ridwan!' )
  Comment.create(post: first_post, author: fourth_user, text: 'How the weather ?' )
  Comment.create(post: second_post, author: fourth_user, text: 'How the weather ?' )
  Comment.create(post: second_post, author: fourth_user, text: 'How the weather ?' )
  Comment.create(post: second_post, author: fourth_user, text: 'How the weather ?' )
  Comment.create(post: second_post, author: fourth_user, text: 'How the weather ?' )
  Comment.create(post: second_post, author: fourth_user, text: 'How the weather ?' )
  Comment.create(post: third_post, author: fourth_user, text: 'Its been good to know' )
  Comment.create(post: third_post, author: fourth_user, text: 'Its been good to know' )
  Comment.create(post: third_post, author: fourth_user, text: 'Its been good to know' )
  Comment.create(post: fourth_post, author: fourth_user, text: 'Its been good to know' )
  Comment.create(post: fourth_post, author: fourth_user, text: 'Its been good to know' )
  Comment.create(post: fourth_post, author: fourth_user, text: 'Its been good to know' )
  Comment.create(post: fourth_post, author: fourth_user, text: 'Hi Tom!' )
  Comment.create(post: fourth_post, author: fourth_user, text: 'Hi Tom!' )
  Comment.create(post: fifth_post, author: fourth_user, text: 'Hi Tom!' )
  Comment.create(post: fifth_post, author: fourth_user, text: 'Hello lilly you here too' )
  Comment.create(post: fifth_post, author: fourth_user, text: 'Hello lilly you here too' )
  Comment.create(post: sixth_post, author: fourth_user, text: 'Hello lilly you here too' )
  Comment.create(post: sixth_post, author: fourth_user, text: 'Hello lilly you here too' )
